from __future__ import annotations

from datetime import datetime, timezone

from .models import (
    AccessPoint,
    InternetStatus,
    LanDevice,
    LiveTraffic,
    NearbyNetwork,
    NetworkInterface,
    PortCount,
    RemoteTalker,
    RouteInfo,
    Snapshot,
    SocketFlow,
    SystemInfo,
    TrafficPoint,
    TrafficSample,
    WirelessLink,
)
from .vendors import vendor_from_mac


def demo_snapshot(base: Snapshot) -> Snapshot:
    """Fill wireless-centric sections with a realistic home network."""
    now = datetime.now(timezone.utc).isoformat()
    link = WirelessLink(
        interface="wlan0",
        connected=True,
        ssid="Corbin-Home",
        bssid="78:8a:20:4c:21:a1",
        frequency_mhz=5180,
        channel=36,
        band="5 GHz",
        signal_dbm=-49,
        noise_dbm=-92,
        link_quality="61/70",
        link_quality_percent=87.1,
        tx_bitrate_mbps=866.7,
        rx_bitrate_mbps=866.7,
        tx_power_dbm=31,
        mode="Managed",
        security="WPA2/WPA3",
        power_save=True,
        tx_retries=4,
        invalid_misc=0,
        missed_beacons=0,
        beacon_interval=100,
        dtim_period=3,
    )
    ap = AccessPoint(
        ssid=link.ssid,
        bssid=link.bssid,
        vendor=vendor_from_mac(link.bssid),
        channel=link.channel,
        frequency_mhz=link.frequency_mhz,
        band=link.band,
        signal_dbm=link.signal_dbm,
        security=link.security,
        pairwise_ciphers=["CCMP"],
        group_cipher="CCMP",
        auth_suites=["PSK", "SAE"],
        hidden=False,
    )
    nearby = [
        NearbyNetwork(
            **ap.model_dump(),
            is_associated=True,
            is_duplicate_ssid=True,
            width_mhz=80,
        ),
        NearbyNetwork(
            ssid="Corbin-Home",
            bssid="78:8a:20:4c:21:a2",
            vendor="Ubiquiti",
            channel=149,
            frequency_mhz=5745,
            band="5 GHz",
            signal_dbm=-63,
            security="WPA2/WPA3",
            pairwise_ciphers=["CCMP"],
            group_cipher="CCMP",
            auth_suites=["PSK", "SAE"],
            is_duplicate_ssid=True,
            width_mhz=80,
        ),
        NearbyNetwork(
            ssid="Corbin-Home",
            bssid="78:8a:20:4c:21:a3",
            vendor="Ubiquiti",
            channel=36,
            frequency_mhz=5180,
            band="5 GHz",
            signal_dbm=-58,
            security="WPA2/WPA3",
            is_duplicate_ssid=True,
            width_mhz=80,
        ),
        NearbyNetwork(
            ssid="Corbin-Home",
            bssid="78:8a:20:4c:21:b1",
            vendor="Ubiquiti",
            channel=44,
            frequency_mhz=5220,
            band="5 GHz",
            signal_dbm=-67,
            security="WPA2/WPA3",
            is_duplicate_ssid=True,
            width_mhz=80,
        ),
        NearbyNetwork(
            ssid="Corbin-Home",
            bssid="78:8a:20:4c:21:c4",
            vendor="Ubiquiti",
            channel=6,
            frequency_mhz=2437,
            band="2.4 GHz",
            signal_dbm=-72,
            security="WPA2/WPA3",
            is_duplicate_ssid=True,
            width_mhz=20,
        ),
        NearbyNetwork(
            ssid="Corbin-Home",
            bssid="f0:9f:c2:10:88:01",
            vendor="Ubiquiti",
            channel=11,
            frequency_mhz=2462,
            band="2.4 GHz",
            signal_dbm=-81,
            security="WPA2/WPA3",
            is_duplicate_ssid=True,
            width_mhz=20,
        ),
        NearbyNetwork(
            ssid="xfinitywifi",
            bssid="7c:2e:bd:11:08:c4",
            vendor="Google",
            channel=6,
            frequency_mhz=2437,
            band="2.4 GHz",
            signal_dbm=-71,
            security="Open",
            hidden=False,
        ),
        NearbyNetwork(
            ssid="NETGEAR-Guest",
            bssid="20:4e:7f:90:12:44",
            vendor="Netgear",
            channel=11,
            frequency_mhz=2462,
            band="2.4 GHz",
            signal_dbm=-78,
            security="WPA2-PSK",
            pairwise_ciphers=["CCMP"],
            group_cipher="CCMP",
            auth_suites=["PSK"],
        ),
        NearbyNetwork(
            ssid=None,
            bssid="a0:63:91:22:10:0b",
            vendor="NETGEAR",
            channel=44,
            frequency_mhz=5220,
            band="5 GHz",
            signal_dbm=-82,
            security="WPA2-PSK",
            hidden=True,
        ),
        NearbyNetwork(
            ssid="OldLinksys",
            bssid="c8:3a:35:01:aa:10",
            vendor="Tenda",
            channel=1,
            frequency_mhz=2412,
            band="2.4 GHz",
            signal_dbm=-86,
            security="WEP",
        ),
        NearbyNetwork(
            ssid="Cafe-Free",
            bssid="50:c7:bf:77:02:19",
            vendor="TP-Link",
            channel=6,
            frequency_mhz=2437,
            band="2.4 GHz",
            signal_dbm=-88,
            security="Open",
        ),
    ]
    devices = [
        LanDevice(
            ip="192.168.1.1",
            mac="78:8a:20:4c:21:a1",
            vendor="Ubiquiti",
            hostname="udm-pro",
            interface="wlan0",
            state="REACHABLE",
            is_gateway=True,
        ),
        LanDevice(
            ip="192.168.1.24",
            mac="d8:3a:dd:5e:10:22",
            vendor="Raspberry Pi",
            hostname="wifi-monitor",
            interface="wlan0",
            state="REACHABLE",
            is_self=True,
        ),
        LanDevice(
            ip="192.168.1.18",
            mac="88:1f:a1:9c:44:10",
            vendor="Apple",
            hostname="roberts-macbook",
            interface="wlan0",
            state="REACHABLE",
        ),
        LanDevice(
            ip="192.168.1.32",
            mac="a4:83:e7:02:11:8c",
            vendor="Apple",
            hostname="iphone",
            interface="wlan0",
            state="STALE",
            new=True,
        ),
        LanDevice(
            ip="192.168.1.40",
            mac="ac:3a:7a:88:21:03",
            vendor="Roku",
            hostname="living-room-tv",
            interface="wlan0",
            state="REACHABLE",
        ),
        LanDevice(
            ip="192.168.1.55",
            mac="18:b4:30:6a:01:f2",
            vendor="Nest",
            hostname="thermostat",
            interface="wlan0",
            state="DELAY",
        ),
    ]
    if not base.interfaces:
        interfaces = [
            NetworkInterface(
                name="wlan0",
                mac="d8:3a:dd:5e:10:22",
                state="up",
                mtu=1500,
                ipv4=["192.168.1.24/24"],
                ipv6=["fe80::da3a:ddff:fe5e:1022/64"],
                rx_bytes=482331001,
                tx_bytes=31822044,
                rx_packets=644201,
                tx_packets=210334,
                is_wireless=True,
                is_default=True,
            ),
            NetworkInterface(
                name="eth0",
                mac="e4:5f:01:22:10:ab",
                state="down",
                mtu=1500,
                is_wireless=False,
            ),
            NetworkInterface(
                name="lo",
                mac="00:00:00:00:00:00",
                state="up",
                mtu=65536,
                ipv4=["127.0.0.1/8"],
                ipv6=["::1/128"],
            ),
        ]
    else:
        interfaces = base.interfaces

    routes = base.routes or [
        RouteInfo(
            destination="default",
            gateway="192.168.1.1",
            interface="wlan0",
            metric=600,
            protocol="dhcp",
            source="192.168.1.24",
        ),
        RouteInfo(
            destination="192.168.1.0/24",
            interface="wlan0",
            protocol="kernel",
            source="192.168.1.24",
        ),
    ]
    internet = InternetStatus(
        online=True,
        public_ip="73.184.12.40",
        dns_ok=True,
        dns_servers=["192.168.1.1", "1.1.1.1"],
        dns_resolved=["142.250.190.78"],
        ping_targets=[
            {
                "host": "1.1.1.1",
                "ok": True,
                "rtt_avg_ms": 14.2,
                "packet_loss_percent": 0,
            },
            {
                "host": "8.8.8.8",
                "ok": True,
                "rtt_avg_ms": 18.6,
                "packet_loss_percent": 0,
            },
        ],
        latency_ms=16.4,
        packet_loss_percent=0,
        gateway_reachable=True,
    )
    traffic = [
        TrafficSample(
            interface="wlan0",
            rx_bps=2_450_000,
            tx_bps=180_000,
            rx_bytes=482331001,
            tx_bytes=31822044,
        )
    ]
    history = list(base.history)
    if len(history) < 12:
        import math

        now_ts = datetime.now(timezone.utc).timestamp()
        history = [
            TrafficPoint(
                ts=now_ts - (59 - i) * 5,
                rx_bps=1_800_000 + math.sin(i / 6) * 600_000,
                tx_bps=120_000 + math.cos(i / 8) * 40_000,
                signal_dbm=-48 - abs(math.sin(i / 9)) * 4,
            )
            for i in range(60)
        ]
    system = base.system.model_copy(
        update={
            "hostname": base.system.hostname or "wifi-monitor",
            "model": base.system.model or "Raspberry Pi 5 Model B Rev 1.0",
            "app_version": base.system.app_version or "1.0.0",
        }
    )
    if system.model is None:
        system = SystemInfo(**{**system.model_dump(), "model": "Raspberry Pi 5 Model B Rev 1.0"})

    live_traffic = LiveTraffic(
        captured_at=now,
        source="demo",
        established=7,
        listen=3,
        udp=4,
        syn_sent=2,
        unique_remotes=9,
        wan_remotes=6,
        lan_remotes=3,
        flows=[
            SocketFlow(
                protocol="tcp",
                state="ESTABLISHED",
                local_ip="192.168.1.24",
                local_port=44312,
                remote_ip="1.1.1.1",
                remote_port=443,
                service="https",
                direction="outbound",
                scope="wan",
            ),
            SocketFlow(
                protocol="tcp",
                state="ESTABLISHED",
                local_ip="192.168.1.24",
                local_port=53110,
                remote_ip="8.8.8.8",
                remote_port=53,
                service="dns",
                direction="outbound",
                scope="wan",
                unusual=True,
                notes=["DNS to a public resolver that is not the only server DHCP advertised."],
            ),
            SocketFlow(
                protocol="tcp",
                state="ESTABLISHED",
                local_ip="192.168.1.24",
                local_port=22,
                remote_ip="192.168.1.18",
                remote_port=51244,
                service="ssh",
                direction="inbound",
                scope="lan",
            ),
            SocketFlow(
                protocol="tcp",
                state="ESTABLISHED",
                local_ip="192.168.1.24",
                local_port=44190,
                remote_ip="192.168.1.1",
                remote_port=443,
                service="https",
                direction="outbound",
                scope="lan",
            ),
            SocketFlow(
                protocol="tcp",
                state="ESTABLISHED",
                local_ip="192.168.1.24",
                local_port=39001,
                remote_ip="203.0.113.50",
                remote_port=23,
                service="telnet",
                direction="outbound",
                scope="wan",
                unusual=True,
                new=True,
                notes=["Cleartext telnet to a public address. Confirm this is a device you manage."],
            ),
            SocketFlow(
                protocol="tcp",
                state="SYN_SENT",
                local_ip="192.168.1.24",
                local_port=39040,
                remote_ip="198.51.100.20",
                remote_port=445,
                service="smb",
                direction="outbound",
                scope="wan",
                unusual=True,
                new=True,
                notes=["Outbound SMB never completed. File-sharing to the internet is rarely intended."],
            ),
            SocketFlow(
                protocol="tcp",
                state="SYN_SENT",
                local_ip="192.168.1.24",
                local_port=39041,
                remote_ip="198.51.100.21",
                remote_port=445,
                service="smb",
                direction="outbound",
                scope="wan",
                unusual=True,
                new=True,
            ),
            SocketFlow(
                protocol="udp",
                state="UNCONN",
                local_ip="192.168.1.24",
                local_port=5353,
                remote_ip="224.0.0.251",
                remote_port=5353,
                service="mdns",
                direction="outbound",
                scope="lan",
            ),
            SocketFlow(
                protocol="tcp",
                state="ESTABLISHED",
                local_ip="192.168.1.24",
                local_port=45100,
                remote_ip="13.32.10.4",
                remote_port=443,
                service="https",
                direction="outbound",
                scope="wan",
                new=True,
            ),
        ],
        listeners=[
            SocketFlow(
                protocol="tcp",
                state="LISTEN",
                local_ip="0.0.0.0",
                local_port=8085,
                service="wifi-monitor",
                direction="listen",
                scope="lan",
                process="uvicorn",
            ),
            SocketFlow(
                protocol="tcp",
                state="LISTEN",
                local_ip="0.0.0.0",
                local_port=22,
                service="ssh",
                direction="listen",
                scope="lan",
                process="sshd",
            ),
            SocketFlow(
                protocol="udp",
                state="UNCONN",
                local_ip="0.0.0.0",
                local_port=5353,
                service="mdns",
                direction="listen",
                scope="lan",
            ),
        ],
        top_remotes=[
            RemoteTalker(ip="192.168.1.1", count=4, ports=[443, 53], scope="lan", service_hint="https"),
            RemoteTalker(ip="1.1.1.1", count=3, ports=[443], scope="wan", service_hint="https"),
            RemoteTalker(ip="8.8.8.8", count=2, ports=[53], scope="wan", service_hint="dns"),
            RemoteTalker(ip="203.0.113.50", count=1, ports=[23], scope="wan", service_hint="telnet"),
        ],
        top_ports=[
            PortCount(port=443, protocol="tcp", count=5, service="https"),
            PortCount(port=53, protocol="tcp", count=2, service="dns"),
            PortCount(port=445, protocol="tcp", count=2, service="smb"),
            PortCount(port=22, protocol="tcp", count=1, service="ssh"),
            PortCount(port=23, protocol="tcp", count=1, service="telnet"),
        ],
    )
    return Snapshot(
        generated_at=now,
        demo=True,
        link=link,
        access_point=ap,
        nearby=nearby,
        devices=devices,
        interfaces=interfaces,
        routes=routes,
        internet=internet,
        traffic=traffic,
        history=history,
        live_traffic=live_traffic,
        system=system,
        gateway_ip="192.168.1.1",
        local_ip="192.168.1.24",
        wireless_interface="wlan0",
        subnet="192.168.1.0/24",
        capabilities={**base.capabilities, "demo": True},
    )
